### ISSUE TITLE
Scan failed wifi networks

### ISSUE THREAD

**Issue by shra1976** [albertogeniola/meross_pair#1]
Hi @albertogeniola I've tried on 2 devices but I have the same error on both. Wifi and gps are on. I've tried both the debug and release apk.

**Comment by albertogeniola** [comment]
Hi @shra1976 ,

thanks for trying the app. What's the error you experience? Can you describe it?

**Comment by shra1976** [comment]
Sorry... The one described in the object... "scan failed wifi networks". Tryed on android 10 and android 6.

**Comment by shra1976** [comment]
The last release works well. Thanks, Marco.

**Comment by hamid-elaosta** [comment]
Hi, I've just installed the latest pre-release on Android 13 and I'm seeing this same issue. When I open the pair page and hit update I get a toast with "scan failed WiFi networks"
