### ISSUE TITLE
unable to install Samsung S10+

### ISSUE THREAD

**Issue by count-jayo** [albertogeniola/meross_pair#5]
Hi Alberto,

Been very keenly watching your work. I'm having issues with the meross pairer that it simply won't install.

I'm on a Samsung S10+ running Android 11.
I have enabled the ability to install unknown APK and have been doing this through Samsung's own file manager. I've tried to install the previous version and this current release.

Interestingly I do have your meross conf APK installed and that is working fine.

**Comment by albertogeniola** [comment]
Hi!

You should first uninstall the previous version. Then you should subscribe formth beta testing here: https://play.google.com/apps/testing/com.albertogeniola.merossconf

That way you will be able to install the current release.

Let me know if that works!

**Comment by count-jayo** [comment]
Hey,

I tried uninstalling meross conf APK but I still can't install the new one. Also the link above tells me the app isn't available for me. Let me know if you need me to send you my email address to be added to a list.

**Comment by albertogeniola** [comment]
Hi @count-jayo ,

please send your email address privately to me, so that I can add you to the beta-testers.

Al

**Comment by count-jayo** [comment]
Hi Alberto,

email address is ***@***.***





Jul 5, 2021, 18:25 by ***@***.***:

**Comment by albertogeniola** [comment]
Hi @count-jayo ,

github censored your email address. In any case, you should now be able to freely join the [public beta](https://play.google.com/apps/testing/com.albertogeniola.merossconf). Try it!
